### ISSUE TITLE
RecyclerView and HashtagView

### ISSUE THREAD

**Issue by claudiopastorini** [greenfrvr/hashtag-view#8]
Hi I have some problems using your library in my project with a RecyclerView (in particular with [Material List](https://github.com/dexafree/MaterialList/)). 
I have a list of cards with some text and HashtagView. The first time the cards are populated in the right way, when I scroll cards are populated in the right way except that HashtagView that reuse previous tags.

I believed that the problem was in your view because I read that you don't call anytime invalidate() when data are setted. After that I added those calls in your code the result is the same. 

So I don't understand where is the problem.. I tried to add some log in your code and when I setData the log works, so I believed that the problem is in the RecyclerView that doesn't redraw your view. I don't know why...

**Comment by greenfrvr** [comment]
I'll try investigate this issue anytime soon.

**Comment by claudiopastorini** [comment]
I implemented an example of use of RecyclerView. See my [fork](https://github.com/pincopallino93/hashtag-view).

I think that the problem occurs because you call draw() only on preDraw(). You should call it every times setData() is called but this compromises everything that you have created XD.

**Comment by greenfrvr** [comment]
Thanks for your RecyclerView example. I solved the problem of using previous tags in RecyclerView that you described, but there is still some issues with setting empty arrays as a data. Currently working on it)

**Comment by claudiopastorini** [comment]
Maybe I solved the issue with empty arrays. I created a dummy ItemData and when it occurs I set the view's visibility to GONE. It keeps crashing with IllegalStateException but I forced it to remove views in draw()'s for and now it doesn't crash anymore. See [here](https://github.com/pincopallino93/hashtag-view/commit/b7e076f).

Now I want to understand how sort() works because it orders in different way the same content during the scrolling. There is also another problem, the scroll is "jerky". I suppose it is caused by the loading of the previous/following row.

**Comment by greenfrvr** [comment]
That's quite tricky issue, I made several fixes which allow handling empty arrays, but it still crashing on fling event.

**Comment by claudiopastorini** [comment]
Did you see my code?

**Comment by greenfrvr** [comment]
Try to pull last updates. It seems the problem is solved. Sorry for such a long pause. Hope your'e still interested in library.
